version: "3.8"

services:
  mongo:
    container_name: mongodb
    image: mongo:4.0.28
    ports:
      - '27017:27017'
    restart: unless-stopped
  redis:
    container_name: redis
    image: redis:6.2.5
    ports:
      - '6379:6379'
    restart: unless-stopped